GraphQL-Portal/graphql-portal-dashboard

- packages/frontend/src/model/GatewayNodes/queries/useGateways.ts
- packages/frontend/src/presenter/GatewayNodes/useGatewayNodes.ts
- packages/frontend/src/ui/Emoji/Emoji.tsx
- packages/frontend/src/ui/Emoji/index.ts
- packages/frontend/src/ui/Emoji/types.ts
- packages/frontend/src/ui/index.ts
- packages/frontend/src/view/GatewayNodes/Empty.tsx
- packages/frontend/src/view/GatewayNodes/GatewayNodes.tsx
- packages/frontend/src/view/GatewayNodes/List.tsx
- packages/frontend/src/view/GatewayNodes/types.ts
- packages/frontend/src/view/GatewayNodes/useStyles.ts
- add Emoji component
- add Empty Gateway page
- split Gateway Nodes page view to Empty and List
> [F] empty gateway nodes page

- packages/frontend/src/ui/Spinner/Spinner.tsx
- packages/frontend/src/ui/Spinner/index.ts
- packages/frontend/src/ui/index.ts
- packages/frontend/src/view/GatewayNodes/GatewayNodes.tsx
- packages/frontend/src/view/Loading/Loading.tsx
- packages/frontend/src/view/Loading/index.ts
- packages/frontend/src/view/Loading/useStyles.ts
- add Spinner component
- add Loading screen view
- implement loading on Gateway Nodes screen
> [F] basic loading screen

- .github/workflows/test.yml
- packages/frontend/src/App.tsx
- packages/frontend/src/model/providers/Auth/AuthProvider.tsx
- packages/frontend/src/model/providers/Auth/index.ts
- packages/frontend/src/model/providers/Router/routes.ts
- packages/frontend/src/model/providers/Theme/theme.ts
- packages/frontend/src/model/providers/index.ts
- packages/frontend/src/presenter/GatewayNodes/useGatewayNodes.ts
- packages/frontend/src/ui/Input/Input.tsx
- packages/frontend/src/ui/Input/index.ts
- packages/frontend/src/ui/Widgets/Widget.tsx
- packages/frontend/src/ui/Widgets/index.ts
- packages/frontend/src/ui/Widgets/types.ts
- packages/frontend/src/ui/index.ts
- packages/frontend/src/view/Content/Content.tsx
- packages/frontend/src/view/Content/types.ts
- packages/frontend/src/view/Login/Login.tsx
- packages/frontend/src/view/Login/index.ts
- packages/frontend/src/view/Login/useStyles.ts
- packages/frontend/src/view/ProtectedRoutes/ProtectedRoutes.tsx
- packages/frontend/src/view/ProtectedRoutes/index.ts
- packages/frontend/src/view/index.ts
- add Input component
- add Protected routes
- add Login form
> [F] auth flow

- packages/frontend/src/ui/Input/Input.tsx
- packages/frontend/src/ui/Switch/Switch.tsx
- packages/frontend/src/ui/Switch/index.ts
- packages/frontend/src/ui/Switch/types.ts
- packages/frontend/src/ui/Switch/useStyles.ts
- packages/frontend/src/ui/index.ts
- packages/frontend/src/view/Login/Login.tsx
- packages/frontend/src/view/index.ts
> [F] add Switch component

- packages/frontend/package.json
- packages/frontend/src/presenter/Login/index.ts
- packages/frontend/src/presenter/Login/useLogin.ts
- packages/frontend/src/ui/Input/Input.tsx
- packages/frontend/src/view/Login/Login.tsx
- yarn.lock
- add vest for form validation
- add validation to login form
> [F] auth form validation

- packages/frontend/package.json
- packages/frontend/src/App.tsx
- packages/frontend/src/hooks/index.ts
- packages/frontend/src/hooks/useFormErrors.ts
- packages/frontend/src/model/providers/Toast/Toast.tsx
- packages/frontend/src/model/providers/Toast/ToastProvider.tsx
- packages/frontend/src/model/providers/Toast/index.ts
- packages/frontend/src/model/providers/Toast/types.ts
- packages/frontend/src/model/providers/Toast/useToast.ts
- packages/frontend/src/model/providers/index.ts
- packages/frontend/src/presenter/Login/useLogin.ts
- packages/frontend/src/ui/Errors/Errors.tsx
- packages/frontend/src/ui/Errors/List.tsx
- packages/frontend/src/ui/Errors/index.ts
- packages/frontend/src/ui/Errors/useStyles.ts
- packages/frontend/src/ui/Snackbar/Snackbar.tsx
- packages/frontend/src/ui/Snackbar/index.ts
- packages/frontend/src/ui/Snackbar/types.ts
- packages/frontend/src/ui/Snackbar/useStyles.ts
- packages/frontend/src/ui/index.ts
- yarn.lock
> [F] toast component

- packages/frontend/src/presenter/DataSources/constants.ts
- packages/frontend/src/presenter/DataSources/helpers.ts
- packages/frontend/src/presenter/DataSources/useAvailableSources.ts
- packages/frontend/src/utils/compose.ts
- packages/frontend/src/utils/getPath.ts
- packages/frontend/src/utils/getProp.ts
- packages/frontend/src/utils/index.ts
- packages/frontend/src/view/DataSources/DataSources/AvailableList.tsx
- get list of available data-sources from `definitions.Handlers`
> [F] fix list of available data sources

- packages/frontend/src/App.tsx
- packages/frontend/src/model/providers/Dialogs/Dialogs.tsx
- packages/frontend/src/model/providers/Dialogs/index.ts
- packages/frontend/src/model/providers/index.ts
- packages/frontend/src/types/Dialogs.ts
- packages/frontend/src/types/index.ts
- packages/frontend/src/ui/Dialogs/Dialog.tsx
- packages/frontend/src/ui/Dialogs/DialogText.tsx
- packages/frontend/src/ui/Dialogs/DialogTitle.tsx
- packages/frontend/src/ui/Dialogs/index.ts
- packages/frontend/src/ui/Dialogs/useStyles.ts
- packages/frontend/src/ui/Typography/Body1.tsx
- packages/frontend/src/ui/Typography/index.ts
- packages/frontend/src/ui/index.ts
- packages/frontend/src/view/DataSources/DeleteDataSource/DeleteDataSource.tsx
- packages/frontend/src/view/DataSources/DeleteDataSource/index.ts
- packages/frontend/src/view/Dialogs/Modal/ModalDialog.tsx
- packages/frontend/src/view/Dialogs/Modal/index.ts
- packages/frontend/src/view/Dialogs/Modal/useStyles.ts
- packages/frontend/src/view/Dialogs/constants.ts
- packages/frontend/src/view/Dialogs/index.ts
- Create components for Dialogs
> [F] Dialogs

- packages/frontend/src/model/Hooks/index.ts
- packages/frontend/src/model/Hooks/useTabs.ts
- packages/frontend/src/types/Tabs.ts
- packages/frontend/src/types/index.ts
- packages/frontend/src/ui/Tabs/TabsBody.tsx
- packages/frontend/src/ui/Tabs/TabsHead.tsx
- packages/frontend/src/ui/Tabs/helpers.ts
- packages/frontend/src/ui/Tabs/index.ts
- packages/frontend/src/ui/Tabs/useStyles.ts
- packages/frontend/src/ui/index.ts
- packages/frontend/src/view/MyAPI/Create/Create.tsx
- TabsHead and TabsBody component
- useTabs hook
> [F] Tabs component

- package.json
- packages/frontend/src/model/ApiDefs/commands/useCreateApiDef.ts
- packages/frontend/src/model/ApiDefs/commands/useDeleteApiDef.ts
- packages/frontend/src/model/DataSources/commands/useCreateSource.ts
- packages/frontend/src/model/DataSources/commands/useDeleteSource.ts
- packages/frontend/src/model/DataSources/commands/useUpdateSource.ts
- packages/frontend/src/model/DataSources/queries/useSources.ts
- packages/frontend/src/model/GatewayNodes/queries/useGateways.ts
- packages/frontend/src/model/Login/commands/useLogin.ts
- packages/frontend/src/model/ResetPassword/commands/useResetPassword.ts
- packages/frontend/src/model/ResetPasswordRequest/commands/useResetPasswordRequest.ts
- packages/frontend/src/model/SignUp/commands/useSignUp.ts
- packages/frontend/src/model/Users/commands/useBlockUser.ts
- packages/frontend/src/model/Users/commands/useCreateUser.ts
- packages/frontend/src/model/Users/commands/useDeleteUser.ts
- packages/frontend/src/model/Users/commands/useUnblockUser.ts
- packages/frontend/src/model/Users/commands/useUpdateUser.ts
- packages/frontend/src/model/Users/queries/useUsers.ts
- packages/frontend/src/presenter/DataSources/helpers/index.ts
- packages/frontend/src/presenter/DataSources/helpers/sortSourcesByName.ts
- packages/frontend/src/presenter/DataSources/useDataSources.ts
- packages/frontend/src/types/Apollo.ts
- packages/frontend/src/types/index.ts
- add types for useQuery and useMutation options
- move sortDataSourcesByName to `presenter/helpers`
- change sort direction `Z -> A` to `A -> Z`
> [F] types for useQuery and useMutation

- packages/frontend/src/presenter/Login/useLogin.ts
- packages/frontend/src/types/Auth.ts
- packages/frontend/src/types/HookForm.ts
- packages/frontend/src/types/index.ts
- packages/frontend/src/ui/Input/Input.tsx
- packages/frontend/src/view/Login/Login.tsx
- use `register` over `control + Controller`
- add typings to useLogin
- move types to `./src/types`
> [F] login form with uncontroled inputs

- packages/frontend/src/ui/Buttons/Icon.tsx
- packages/frontend/src/view/DataSources/DataSources/AvailableList.tsx
- packages/frontend/src/view/DataSources/DataSources/ConnectedList.tsx
- packages/frontend/src/view/DataSources/SourceTransforms/List.tsx
- packages/frontend/src/view/Form/ObjectArray/ObjectArray.tsx
- packages/frontend/src/view/Form/StringArray/StringArray.tsx
- packages/frontend/src/view/MyAPI/MyApi/List.tsx
- packages/frontend/src/view/Users/List.tsx
- wrap IconButton with forwardRef
- remove useless markup `span` and `div`
> [F] wrap IconButton by forwardRef

- packages/frontend/src/presenter/ApiDefs/index.ts
- packages/frontend/src/presenter/ApiDefs/useDeleteAPI.ts
- packages/frontend/src/presenter/ApiDefs/useMyApi.ts
- packages/frontend/src/types/Api.ts
- packages/frontend/src/view/Dialogs/constants.ts
- packages/frontend/src/view/MyAPI/DeleteAPI/DeleteAPI.tsx
- packages/frontend/src/view/MyAPI/DeleteAPI/index.ts
- packages/frontend/src/view/MyAPI/DeleteAPI/useStyles.ts
- packages/frontend/src/view/MyAPI/MyApi/List.tsx
- packages/frontend/src/view/MyAPI/MyApi/MyAPI.tsx
> [F] show delete api Dialog after click on Button

- packages/frontend/src/model/GatewayNodes/queries/useGateways.ts
- packages/frontend/src/model/providers/State/createClient.ts
- set gateway polling interval to 10 sek
- remove wsLink and wsAuthLink
> [F] set gateway nodes polling to 10 sek

- packages/frontend/src/ui/ButtonGroup/ButtonGroup.tsx
- packages/frontend/src/utils/getKeyFromText.ts
- add keys to buttons in ButtonGroup
- make keys more unique
> [F] add keys to buttons in ButtonGroup

- packages/frontend/src/presenter/ApiDefs/index.ts
- packages/frontend/src/presenter/ApiDefs/useUpdateDataSources.ts
- packages/frontend/src/presenter/ApiDefs/useUpdateGeneral.ts
- packages/frontend/src/presenter/ApiDefs/useUpdateIPFiltering.ts
- packages/frontend/src/presenter/ApiDefs/useUpdateSchemaAndLimits.ts
- packages/frontend/src/types/Api/hooks.ts
- packages/frontend/src/view/MyAPI/Edit/Edit.tsx
- packages/frontend/src/view/MyAPI/Edit/IPTab.tsx
- packages/frontend/src/view/MyAPI/constants.ts
- add IP Filtering form for ApiDef
> [F] edit IP Filtering for ApiDef

- packages/frontend/src/model/ApiDefs/commands/useCreateApiDef.ts
- packages/frontend/src/model/ApiDefs/commands/useUpdateApiDef.ts
- packages/frontend/src/model/GatewayNodes/queries/useGateways.ts
- packages/frontend/src/presenter/ApiDefs/helpers/createFetcher.ts
- packages/frontend/src/presenter/ApiDefs/helpers/createRateLimitPayload.ts
- packages/frontend/src/presenter/ApiDefs/helpers/getUrlFromGatewayNodes.ts
- packages/frontend/src/presenter/ApiDefs/helpers/index.ts
- packages/frontend/src/presenter/ApiDefs/useCreateApi.ts
- packages/frontend/src/presenter/ApiDefs/useUpdateSchemaAndLimits.ts
- packages/frontend/src/presenter/ApiDefs/useViewAPI.ts
- packages/frontend/src/presenter/GatewayNodes/helpers.ts
- packages/frontend/src/presenter/GatewayNodes/useGatewayNodes.ts
- packages/frontend/src/types/Gateway.ts
- packages/frontend/src/view/GatewayNodes/List.tsx
- packages/frontend/src/view/MyAPI/View/View.tsx
- refactor GatewayNode
- get ApiDef URI from GatewayNode
> Get ApiDef URI from GatewayNode

- packages/frontend/src/presenter/DataSources/helpers/createTransformList.ts
- packages/frontend/src/presenter/DataSources/helpers/index.ts
- packages/frontend/src/presenter/DataSources/index.ts
- packages/frontend/src/presenter/DataSources/usePrefixTransform.ts
- packages/frontend/src/presenter/DataSources/useRenameTransform.ts
- packages/frontend/src/presenter/DataSources/useTransformEditors.ts
- packages/frontend/src/types/DataSource/forms.ts
- packages/frontend/src/types/DataSource/hooks.ts
- packages/frontend/src/types/React.ts
- packages/frontend/src/view/DataSources/Layout/HandlerCol.tsx
- packages/frontend/src/view/DataSources/RenameTransform/RenameTransform.tsx
- packages/frontend/src/view/DataSources/RenameTransform/index.ts
- packages/frontend/src/view/DataSources/RenameTransform/useStyles.ts
- packages/frontend/src/view/DataSources/SourceTransforms/List.tsx
- packages/frontend/src/view/DataSources/SourceTransforms/SourceTransforms.tsx
- add custom form for Rename Transform
- fix transform functionality add/edit/delete
> Custom form for Rename Transform

- packages/frontend/src/presenter/DataSources/index.ts
- packages/frontend/src/presenter/DataSources/useSalesforceHandler.ts
- packages/frontend/src/types/DataSource/forms.ts
- packages/frontend/src/types/DataSource/hooks.ts
- packages/frontend/src/view/DataSources/DataSources/constants.ts
- packages/frontend/src/view/DataSources/SalesforceHandler/SalesforceHandler.tsx
- packages/frontend/src/view/DataSources/SalesforceHandler/index.ts
- packages/frontend/src/view/DataSources/SourceHandler/SourceHandler.tsx
- add Salesforce handler custom form
- add Portal icon to IPAPI handler type
> [F] add custom form for the Salesforce handler

- packages/frontend/src/presenter/DataSources/useRenameTransform.ts
- packages/frontend/src/presenter/DataSources/useTransforms.ts
- packages/frontend/src/types/DataSource/components.ts
- packages/frontend/src/view/DataSources/SourceTransforms/Available.tsx
- packages/frontend/src/view/DataSources/SourceTransforms/SourceTransforms.tsx
- packages/frontend/src/view/DataSources/SourceTransforms/constantst.ts
- packages/frontend/src/view/DataSources/SourceTransforms/useStyles.ts
- packages/frontend/src/view/DataSources/constants.ts
- Available transforms as table instead of select
> [F] available transforms as table

- packages/frontend/src/types/Forms/components.ts
- packages/frontend/src/view/Form/ObjectArray/ObjectArray.tsx
- packages/frontend/src/view/Form/StringArray/StringArray.tsx
- yarn.lock
- keyLabel and valueLabel for ObjectArray
- valueLabel for StringArray
- correct default values
> [F] label props for ObjectArray and StringArray

- Dockerfile
> (fix) Set serving static to true for Dockerfile

- packages/frontend/src/icons/index.ts
- packages/frontend/src/model/Users/queries/index.ts
- packages/frontend/src/model/Users/queries/useProfile.ts
- packages/frontend/src/model/providers/Router/routes.ts
- packages/frontend/src/presenter/Users/helpers.ts
- packages/frontend/src/presenter/Users/index.ts
- packages/frontend/src/presenter/Users/useProfile.ts
- packages/frontend/src/types/User.ts
- packages/frontend/src/view/Navigation/Main/constants.ts
- packages/frontend/src/view/Profile/Profile.tsx
- packages/frontend/src/view/Profile/index.ts
- packages/frontend/src/view/Profile/useStyles.ts
- packages/frontend/src/view/ProtectedRoutes/ProtectedRoutes.tsx
> [F] user profile page

- packages/backend/package.json
- yarn.lock
> [F] fix appollo-server-express deps

- .changeset/rare-buses-repeat.md
- packages/frontend/src/ui/Snackbar/Snackbar.tsx
- packages/frontend/src/ui/Snackbar/useStyles.ts
- add Close button for error message
- remove `autoHideDuration` for error message
> [F] error button for error messages

- .changeset/tiny-carrots-begin.md
- packages/frontend/src/view/ApiDefs/View/Playground.tsx
- packages/frontend/src/view/ApiDefs/View/useStyles.ts
> [F] playground styles

- .changeset/sour-cougars-cover.md
- packages/frontend/src/types/Forms/components.ts
- packages/frontend/src/ui/Form/FormLabel.tsx
- packages/frontend/src/ui/Form/FormLabelStart.tsx
- packages/frontend/src/ui/Form/index.ts
- packages/frontend/src/ui/Form/useStyles.ts
- packages/frontend/src/view/ApiDefs/Edit/EditHeader.tsx
- packages/frontend/src/view/ApiDefs/Form/CacheTransforms.tsx
- packages/frontend/src/view/ApiDefs/Form/General.tsx
- packages/frontend/src/view/ApiDefs/Form/IP.tsx
- packages/frontend/src/view/ApiDefs/Form/Schema.tsx
- packages/frontend/src/view/ApiDefs/Form/useStyles.ts
- packages/frontend/src/view/DataSources/GRPCHandler/GRPCHandler.tsx
- packages/frontend/src/view/DataSources/GraphQLHandler/GraphQLHandler.tsx
- packages/frontend/src/view/DataSources/Neo4jHandler/Neo4jHandler.tsx
- packages/frontend/src/view/DataSources/OdataHandler/OdataHandler.tsx
- packages/frontend/src/view/DataSources/OpenapiHandler/OpenapiHandler.tsx
- packages/frontend/src/view/DataSources/PostGraphileHandler/PostGraphileHandler.tsx
- packages/frontend/src/view/DataSources/PrefixTransform/PrefixTransform.tsx
- packages/frontend/src/view/DataSources/RenameTransform/RenameTransform.tsx
- packages/frontend/src/view/DataSources/ThriftHandler/ThriftHandler.tsx
- Abstract over `FormControlLabel` from `@material-ui/core`
- Create FormLabel and FormLabelStart component
- Replace all form labels with new components
> [F] abstract over FormLabel

- packages/frontend/src/presenter/DataSources/useJsonSchemaHandler.ts
- packages/frontend/src/types/DataSource/components.ts
- packages/frontend/src/types/DataSource/data.ts
- packages/frontend/src/types/DataSource/forms.ts
- packages/frontend/src/types/DataSource/hooks.ts
- packages/frontend/src/view/DataSources/JsonSchemaHandler/ArgsTypeMap.tsx
- packages/frontend/src/view/DataSources/JsonSchemaHandler/JsonSchemaHandler.tsx
- packages/frontend/src/view/DataSources/JsonSchemaHandler/Operations.tsx
- typings for JsonSchema components and hook
- rearrange form fields
- add argTypeMap fieldArray
> [F] JsonSchema form with argTypeMap and fields rearrangement

- .changeset/unlucky-olives-jog.md
- packages/frontend/src/presenter/DataSources/index.ts
- packages/frontend/src/presenter/DataSources/useFilterTransform.ts
- packages/frontend/src/types/DataSource/forms.ts
- packages/frontend/src/types/DataSource/hooks.ts
- packages/frontend/src/view/DataSources/FilterTransform/FilterTransform.tsx
- packages/frontend/src/view/DataSources/FilterTransform/index.ts
- packages/frontend/src/view/DataSources/FilterTransform/useStyles.ts
- packages/frontend/src/view/DataSources/SourceTransforms/SourceTransforms.tsx
- add custom form for Filter Transform
> [F] add custom Filter Transform

- packages/frontend/src/presenter/DataSources/index.ts
- packages/frontend/src/presenter/DataSources/useFilterTransform.ts
- packages/frontend/src/presenter/DataSources/useNamingConventionTransform.ts
- packages/frontend/src/types/DataSource/forms.ts
- packages/frontend/src/types/DataSource/hooks.ts
- packages/frontend/src/ui/Select/Select.tsx
- packages/frontend/src/view/DataSources/AddDataSource/AddDataSource.tsx
- packages/frontend/src/view/DataSources/DataSources/AvailableList.tsx
- packages/frontend/src/view/DataSources/NamingConventionTransform/NamingConventionTransform.tsx
- packages/frontend/src/view/DataSources/NamingConventionTransform/index.ts
- packages/frontend/src/view/DataSources/NamingConventionTransform/useStyles.ts
- packages/frontend/src/view/DataSources/SourceTransforms/SourceTransforms.tsx
- packages/frontend/src/view/Form/ObjectArray/ObjectArray.tsx
- custom form for NamingConventionTransform
- fix bugs with key in React components
> [F] Naming Convention Transform handler

- .changeset/clean-dogs-check.md
- packages/frontend/src/presenter/DataSources/index.ts
- packages/frontend/src/presenter/DataSources/useSlackHandler.ts
- packages/frontend/src/types/DataSource/forms.ts
- packages/frontend/src/types/DataSource/hooks.ts
- packages/frontend/src/view/DataSources/SlackHandler/SlackHandler.tsx
- packages/frontend/src/view/DataSources/SlackHandler/index.ts
- packages/frontend/src/view/DataSources/SourceHandler/SourceHandler.tsx
> [F] add Slack Handler form
